"""added order to db model

Revision ID: 36f26b4653cd
Revises: 
Create Date: 2019-12-27 05:51:47.806921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f26b4653cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('gid', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_customer_first_name'), 'customer', ['first_name'], unique=False)
    op.create_index(op.f('ix_customer_last_name'), 'customer', ['last_name'], unique=False)
    op.create_table('order',
    sa.Column('gid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_table('product',
    sa.Column('gid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('variant',
    sa.Column('gid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('product_gid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['product_gid'], ['product.gid'], ),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_variant_name'), 'variant', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_name'), table_name='variant')
    op.drop_table('variant')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_index(op.f('ix_customer_last_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_first_name'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
